### ISSUE TITLE
Wrong dll/implib generation rule

### ISSUE THREAD

**Issue by TimothyGu** [dlfcn-win32/dlfcn-win32#1]
Migrated from: https://code.google.com/p/dlfcn-win32/issues/detail?id=15

Reported by: @LRN on April 24, 2014.

---

What steps will reproduce the problem?
1. build a shared library

What is the expected output? What do you see instead?
Expected:
libdl.dll - a PE shlib
libdl.dll.a - an import library for that shlib
Got:
libdl.dll - a PE shlib
libdl.dll.a - a PE shlib

What version of the product are you using? On what operating system?
Windows, SVN HEAD

Please provide any additional information below.
Wrong rule in the makefile (most likely a result of a few separate changes over time).

---

Patch proposed:

```diff
--- Makefile.orig	2014-04-24 07:41:47.398326500 +0000
+++ Makefile	2014-04-24 07:43:23.502530200 +0000
@@ -30,9 +30,11 @@
 	$(AR) cru $@ $^
 	$(RANLIB) libdl.a
 
-libdl.dll libdl.dll.a: $(LIB_OBJS)
+libdl.dll: $(LIB_OBJS)
 	$(CC) $(SHFLAGS) -shared -o $@ $^
 
+libdl.dll.a: libdl.dll
+
 libdl.lib: libdl.dll
 	$(LIBCMD) /machine:i386 /def:libdl.def
 
```

---

@TimothyGu said:

I can't reproduce it here. libdl.dll.a is significantly smaller than libdl.dll and objdump shows that it is correct.

---

@LRN said:

Dunno, maybe it depends on the version and type of `make' program you're using.
The way i see it (and the way msys2-make sees it) is that:
to produce libdl.dll:
  produce $(LIB_OBJS) first
  then
  run $(CC) $(SHFLAGS) -shared -o libdl.dll $(LIB_OBJS)
to produce libdl.dll.a:
  produce $(LIB_OBJS) first
  then
  run $(CC) $(SHFLAGS) -shared -o libdl.dll.a $(LIB_OBJS)

My patch changes the rules into:

to produce libdl.dll:
  produce $(LIB_OBJS) first
  then
  run $(CC) $(SHFLAGS) -shared -o libdl.dll $(LIB_OBJS)

to produce libdl.dll.a:
  produce libdl.dll first

---

@TimothyGu said:

I will probably migrate to autotools soon. Also the new project page is at https://github.com/dlfcn-win32/dlfcn-win32 now. I will spend some time migrating the remaining issues there.

**Comment by xantares** [comment]
hey,
that's what i fixed in 
https://github.com/dlfcn-win32/dlfcn-win32/pull/7

**Comment by xantares** [comment]
@TimothyGu so you find cmake more complex ? cmakelists.txt is ~30 lines, configure+makefile are ~300+ lines of code:

do you find this less complex:
```
%.o: %.c
$(CC) -o $@ -c $< -Wall -O3 -fomit-frame-pointer
```

than that:
```
set (sources dlfcn.c)
add_library (dl ${sources})
```

**Comment by TimothyGu** [comment]
@xantares I've been meant to convert this whole homebrew thing to autotools, but that effort was stalled due to my being busy. CMake is simple for simple projects, but extremely complex once you want to do something other than dynamic linking. I guess for this project it's fine but I'm generally not a fan of it.
