### ISSUE TITLE
config.mak: No such file or directory

### ISSUE THREAD

**Issue by hajsf** [dlfcn-win32/dlfcn-win32#105]
While running `make` command at my Windows 11 machine, I got the error:
```bash
PS D:\Downloads\dlfcn-win32-master\dlfcn-win32-master> make
makefile:4: config.mak: No such file or directory
make: *** No rule to make target `config.mak'.  Stop.
```

Am I missing something?

**Comment by pali** [comment]
> Am I missing something?

Yes, running `./configure` which will generate that file.

**Comment by hajsf** [comment]
> ```shell
> config.mak
> ```

This is something completely new to me. I got the file generated as:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/98168280/177014836-73d9f5af-3225-4f70-9a07-ece155e04a0b.png">

But I got an error:
```bash
PS D:\Downloads\dlfcn-win32-master\dlfcn-win32-master> make
config.mak:13: *** missing separator.  Stop.
```

Do I need to do anything in this generated file, or just saving it as `config.mak`

**Comment by pali** [comment]
You need to **run** this `./configure` script. It will generate `config.mak`.

**Comment by jonaski** [comment]
> ```shell
> PS D:\Downloads\dlfcn-win32-master\dlfcn-win32-master> make
> config.mak:13: *** missing separator.  Stop.
> ```
This is a common problem with GNU autotools on Windows. You are better off using CMake.

**Comment by pali** [comment]
We are not using GNU autotools.

Steps for Makefile build are:
1. run `./configure`
2. run `make`

Another option is to use cmake.
