### ISSUE TITLE
Test on mingw and mingw-w64

### ISSUE THREAD

**Issue by TimothyGu** [dlfcn-win32/dlfcn-win32#15]

**Comment by shviller** [comment]
On MinGW (as opposed to w64; I haven't tested the latter) it fails with ```undefined reference to `sprintf_s'```. It would seem that adding
```
#if ( (defined(_WIN32) || defined(WIN32)   ) && ( ! defined(_MSC_VER)  ) )
#define sprintf_s snprintf
#endif
```
at least lets it build and pass the tests.

**Comment by TimothyGu** [comment]
Nah, I've decided to stop supporting the very old MinGW.

**Comment by pali** [comment]
You do not need to use `snprintf` at all. There is fixed buffer and maximal possible size of formatted output. For this purpose is `sprintf` enough and that function is available in MSVC, old mingw, and also mingw-w64. I included fix in pull request https://github.com/dlfcn-win32/dlfcn-win32/pull/50 -- it removes lot of unneeded #ifdef.
