### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by TimothyGu** [dlfcn-win32/dlfcn-win32#16]

**Comment by traversaro** [comment]
I am looking into packaging this library for [`vcpkg`](https://github.com/Microsoft/vcpkg), and a new release (including the CMake build system) would definitely be handy. Thanks a lot for the library! 

Ref: https://github.com/Microsoft/vcpkg/issues/201

**Comment by traversaro** [comment]
Done in https://github.com/dlfcn-win32/dlfcn-win32/releases/tag/v1.1.0 .
