### ISSUE TITLE
Please specify the dependency to psapi.lib in the README.md

### ISSUE THREAD

**Issue by robertwgh** [dlfcn-win32/dlfcn-win32#18]
Not everyone would download the demo project.
As per my experiment, this is the only library required by dlfcn-win32.
Please explicitly  state this in the README, this could save people tons of time.

**Comment by TimothyGu** [comment]
Yes it is. `psapi` is a standard Windows library so you shouldn't need to know about this unless you are using static library. I will update it soon.

**Comment by robertwgh** [comment]
The easiest way might be adding the following line to dlfcn.c :
#pragma comment(lib,"psapi.lib")

Then, you don't need to care about the library, no matter it is statically or dynamically linked.

**Comment by TimothyGu** [comment]
@robertwgh true. Does that work with MinGW though?

**Comment by robertwgh** [comment]
Not sure about that.
I mean for VS users, that works better. Since the user does not need to
touch any thing regarding to the library itself.
I don't work with MinGW.
I basically have a project compiled under VS2010/2012 and Android ndk.

**Comment by TimothyGu** [comment]
OK I'll take a look.

**Comment by yselkowitz** [comment]
No, `#pragma comment(lib,...)` is a MSVCism not supported by GCC (and hence MinGW).

**Comment by traversaro** [comment]
As correctly mentioned by @yselkowitz , the `#pragma comment(lib,...)` is a MSVCiscm that additionally does not play well with most build systems. I think it make sense to close this, @TimothyGu please reopen if you think otherwise.

**Comment by pali** [comment]
In this pull request https://github.com/dlfcn-win32/dlfcn-win32/pull/51 is removal of link time dependency on psapi.dll and change to runtime dependency. So it is not needed to link psapi.dll anymore. Function from that library is loaded at runtime, but to avoid circle dlopen/dlsym calls are not used :-)
