### ISSUE TITLE
Add dladdr & Dl_info

### ISSUE THREAD

**Issue by raphaelh** [dlfcn-win32/dlfcn-win32#21]
Are you planning to add dladdr & Dl_info support?

Thanks!

**Comment by TimothyGu** [comment]
Neither dladdr nor Dl_info is POSIX.

**Comment by nicowilliams** [comment]
> Neither dladdr nor Dl_info is POSIX.

Eh, it's a common and very useful extension.  One use is for supporting deploy-time relocation of code on the filesystem (e.g., to open asset files relative to install location that is not known at build-time).

I have written a WIN32 version in [Heimdal](https://github.com/heimdal/heimdal), in [lib/roken/dlfcn.hin](https://github.com/heimdal/heimdal/blob/master/lib/roken/dlfcn.hin) and [lib/roken/dlfcn_w32.c](https://github.com/heimdal/heimdal/blob/master/lib/roken/dlfcn_w32.c).

That said, there's no way in WIN32 that I can tell to get a symbol name that an address relates to, only the module's filename.  If anyone knows how to get a symbol name, I'm all ears!

**Comment by pali** [comment]
> there's no way in WIN32 that I can tell to get a symbol name that an address relates to

Ou, we have not known that there is no way :-) and togther with @rhabacker we have implemented it!

dladdr pull request is now ready for merge, see: https://github.com/dlfcn-win32/dlfcn-win32/pull/72

**Comment by pali** [comment]
@nicowilliams: You could probably switch Heimdal to this dlfcn-win32 implementation which supports more features. dladdr() with symbol name support is going to be merged ASAP.

**Comment by nicowilliams** [comment]
Ah, I see that, #72.  I might just switch Heimdal to use this when you've merged #72 (ah, you just did).  The license is compatible, and I do have a use for getting symbol names.

@pali @rhabacker Do you happen to know if the new `dladdr()` in #72 will support `DATA` symbols?

**Comment by pali** [comment]
Now (really now!), I'm going to extend dladdr to support reading symbols also from EXPORT table.

About DATA symbols, I'm not sure where are they stored in PE headers...

**Comment by nicowilliams** [comment]
OK, I can always test it, but I probably won't get to it soon.

**Comment by rhabacker** [comment]
>Do you happen to know if the new `dladdr()` in #72 will support `DATA` symbols?
That has not been tested, but should be possible when the variable is decorated with __declspec(dllexport) and __declspec(dllimport).

**Comment by nicowilliams** [comment]
@rhabacker yes, `dladdr()` too is not guaranteed to work for non-exported symbols, and I assume the same reasons would apply to PE.

For the curious, my immediate need is that I'm modifying a "templating" ASN.1 compiler that produces something like bytecode as named arrays of entries, and I need to either enhance those with additional metadata that... happens to be in their symbolic names anyways, or use `dladdr()` portably 😊.  (I'm inclined to make more of those symbols `static` so they can be stripped and extend the template data structures with the metadata I need, and hope the net effect on object size is roughly neutral or better.  That certainly seems simpler in a way, but using `dladdr()` would do no violence to the template generator, which is a big plus.)  Beyond that, having implemented a partial `dladdr()` for WIN32, I'm naturally curious about the rest of it, and I thank you again for this work.

**Comment by nicowilliams** [comment]
FWIW, I don't get symbol names for pointers to data symbols.  I tried applying the patch from #94 and still.

**Comment by rhabacker** [comment]
> That has not been tested, but should be possible with minor adjustments in a different pr, when the variable is decorated with __declspec(dllexport) and __declspec(dllimport).

I suggest to add a feature request for such support.

**Comment by pali** [comment]
> FWIW, I don't get symbol names for pointers to data symbols.

I have put `__declspec(dllexport) unsigned char big_array[100];` into the library and then in executable I called:
```
__declspec(dllimport) extern unsigned char big_array[100];
...
dladdr(&big_array, &info);
```
and it worked, I get in `info` infromation about library and name of symbol `big_array`.

**Comment by rhabacker** [comment]
> and it worked, I get in `info` infromation about library and name of symbol `big_array`.

Nice to hear. Is this result with or without #94 applied ?

**Comment by pali** [comment]
I tested it only with gcc + #94.
