### ISSUE TITLE
permissions on /tmp/test.c can cause configure failure

### ISSUE THREAD

**Issue by rdp** [dlfcn-win32/dlfcn-win32#22]
./configure: line 157: /tmp/test.c: Permission denied
testing compiler: /Users/rdp2/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32-gcc -shared -o /tmp/test.dll /tmp/test.c
/Users/rdp2/dev/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/lib/gcc/i686-w64-mingw32/4.9.3/../../../../i686-w64-mingw32/bin/ld: cannot open output file /tmp/test.dll: Permission denied
collect2: error: ld returned 1 exit status

this can happen if you build once as one user, then again as another...

**Comment by TimothyGu** [comment]
Hmm...

**Comment by tonytheodore** [comment]
Using `/tmp` can also cause errors when building multiple targets simultaneously.

**Comment by tonytheodore** [comment]
Fixed in #26.

**Comment by TimothyGu** [comment]
Indeed.
