### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by vikramarjun** [dlfcn-win32/dlfcn-win32#23]
We are facing issues in modules that depend on dlfcn-win32. BEcause LGPL is not generally accepted in commercial product. Could you please change the license text to MIT. 

Here is a related issue https://github.com/node-ffi/node-ffi/issues/223

**Comment by vikramarjun** [comment]
I can submit a pull request if you desire.

**Comment by TimothyGu** [comment]
@ramiropolla thoughts?
