### ISSUE TITLE
Make source releases use a fixed URL.

### ISSUE THREAD

**Issue by mingwandroid** [dlfcn-win32/dlfcn-win32#24]
I'm considering adding dlfcn-win32 to crosstool-ng for GCC plugin support (it's one option; perhaps GCC upstream already have something else planned!)

Would it be possible for you to make a new release and also, when you do this from now on, to release the source packages with a URL where the basename matches the final filename? Currently, only the binaries follow this rule:
    `https://github.com/dlfcn-win32/dlfcn-win32/releases/download/v1.0.0/dlfcn-win32-static-1.0.0.tar.gz`

While the sources don't:
    `https://github.com/dlfcn-win32/dlfcn-win32/archive/v1.0.0.tar.gz`

This breaks crosstool-ng's `CT_GetFile` script function.

Thanks a lot!

**Comment by TimothyGu** [comment]
Okay.

**Comment by mingwandroid** [comment]
Thanks. Sorry about the spam from github. Unfortunately, every time I rebase the commit which has a reference to this issue URL in its comment, github updates this page :-(

Do have have an ETA for the next release? I'll push ahead and try to get GCC plugins to work on Windows when that happens.

**Comment by TimothyGu** [comment]
I'll try to do it tomorrow if that’s fine with you.

**Comment by mingwandroid** [comment]
That would be great. Thank you.

**Comment by tonytheodore** [comment]
@mingwandroid, you can use the following url format:

```
# <owner>/<repo>/archive/<tag>/<output filename>
https://github.com/dlfcn-win32/dlfcn-win32/archive/v1.0.0/dlfcn-win32-1.0.0.tar.gz
```

**Comment by traversaro** [comment]
As explained by @tonytheodore , a "fixed" url for the latest release is available : 
* https://github.com/dlfcn-win32/dlfcn-win32/archive/v1.1.0/dlfcn-win32-1.1.0.tar.gz
* https://github.com/dlfcn-win32/dlfcn-win32/archive/v1.1.0/dlfcn-win32-1.1.0.zip
