### ISSUE TITLE
Fix tests in Visual Studio 2015

### ISSUE THREAD

**Issue by traversaro** [dlfcn-win32/dlfcn-win32#28]
See https://ci.appveyor.com/project/traversaro/dlfcn-win32/build/1.0.4 ,

**Comment by TimothyGu** [comment]
Any reason why AppVeyor is running on traversaro/dlfcn-win32 rather than this repo?

**Comment by traversaro** [comment]
Setting up an organization account in `dlfcn-win32` require a separate email and being administrator of the repo, see https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization . I was planning to look into it, but before I wanted to get the tests to work. : )
