### ISSUE TITLE
Fix problem with AppVeyor WebHooks 

### ISSUE THREAD

**Issue by traversaro** [dlfcn-win32/dlfcn-win32#33]
After adding support for AppVeyor, we experienced several problems with AppVeyor GitHub WebHooks [1,2]. 
After a brief check I think this is due to the fact that I added the project to AppVeyor, but I don't have sufficient rights to create WebHooks for the `dlfcn-win32/dlfcn-win32` repo [3]. 
@TimothyGu , I just added you to the `dlfcn-win32` AppVeyor team as an admin, can you check if you are able to add the right WebHooks to this repo? Even removing and re-adding the repo to AppVeyor should be sufficient, thanks. 

[1] : https://github.com/dlfcn-win32/dlfcn-win32/pull/30#issuecomment-287006537
[2] : https://github.com/dlfcn-win32/dlfcn-win32/pull/31#issuecomment-292636397
[3] : https://help.github.com/articles/about-webhooks/

**Comment by TimothyGu** [comment]
I deleted and readded the project.

**Comment by TimothyGu** [comment]
Hmm doesn't seem like webhooks are added automatically to the GitHub repo…

**Comment by traversaro** [comment]
I suspect there is something related to the fact that I created the `dlfcn-win32` AppVeyor account without having the admin rights on the `dlfcn-win32` GitHub organization. I will write to AppVeyor support explaining the problem.

**Comment by TimothyGu** [comment]
@traversaro I've invited you to become an Owner of the @dlfcn-win32 org, hope that helps.

**Comment by traversaro** [comment]
Thanks @TimothyGu , that indeed solved the issue, see https://github.com/dlfcn-win32/dlfcn-win32/pull/35 .
