### ISSUE TITLE
dlerror crashes if called twice, NULL pointer bug

### ISSUE THREAD

**Issue by Fishkin** [dlfcn-win32/dlfcn-win32#34]
dlerror is coded badly. It sets current_error to NULL as per the specs, but if called again, it will use it as source to memcpy.

You need to add this at the beginning of the function:

if(!current_error) return NULL;

**Comment by traversaro** [comment]
Thanks for the report! I hope to address this issue in the next week.

**Comment by Fishkin** [comment]
Yeah, that bug bit me when I compiled a patched MinGW so it supports plugins on Windows, because GCC uses dlerror twice in plugin.c. It works flawlessly when patched with that line, good to know it will be fixed so it won't frustrate someone else. :)

**Comment by TimothyGu** [comment]
@Fishkin Would you mind submitting a pull request?
