### ISSUE TITLE
Not thread-safe

### ISSUE THREAD

**Issue by wm4** [dlfcn-win32/dlfcn-win32#5]
For some reason, library handles are cached (why?), using a global linked list. This makes the exported functions unsafe to use in a multithreaded setting.

**Comment by TimothyGu** [comment]
@wm4 said:

> For some reason, library handles are cached (why?), using a global linked list.

They are cached only when `RTLD_GLOBAL` is specified in `dlopen`, as POSIX [mandates][1]:

> Any object loaded by *dlopen()* that requires relocations against global symbols can reference [...] any objects that were loaded in any *dlopen()* invocation and which specified the RTLD_GLOBAL flag.

> This makes the exported functions unsafe to use in a multithreaded setting.

We never said this project is thread-safe. In fact, in `dlfcn.c` we specifically said that:

```c
/* Note:
 * MSDN says these functions are not thread-safe. We make no efforts to have
 * any kind of thread safety.
 */
```

(Can't seem to find the MSDN page right now but I swear I saw somewhere that they are not thread-safe)

Also, POSIX doesn't say that the functions have to be thread safe anyway.

[1]: http://pubs.opengroup.org/onlinepubs/009695399/functions/dlopen.html
