### ISSUE TITLE
undefined reference to `GetModuleHandleExA'

### ISSUE THREAD

**Issue by akyunus0** [dlfcn-win32/dlfcn-win32#75]
how can i solve this problem.
can you help me?
> $ make all install
gcc -Wall -O3 -fomit-frame-pointer -Wl,--out-implib,libdl.dll.a -DSHARED -shared -o libdl.dll dlfcn.c
dlfcn.c: In function 'dlsym':
dlfcn.c:374:14: warning: implicit declaration of function 'GetModuleHandleExA'; did you mean 'GetModuleHandleA'? [-Wimplicit-function-declaration]
  374 |         if( !GetModuleHandleExA( GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT, (LPCSTR) _ReturnAddress( ), &hCaller ) )
      |              ^~~~~~~~~~~~~~~~~~
      |              GetModuleHandleA
c:/mingw/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: C:\Users\SVC_YU~1.AKI\AppData\Local\Temp\cc96eNlS.o:dlfcn.c:(.text+0x688): undefined reference to `GetModuleHandleExA'
collect2.exe: error: ld returned 1 exit status
make: *** [libdl.dll] Error 1

**Comment by pali** [comment]
Try to compile with `-D_WIN32_WINNT=0x0501`

**Comment by akyunus0** [comment]
How do i say Compile with `-D_WIN32_WINNT=0x0501`

**Comment by pali** [comment]
you can set it in CPPFLAGS variable. or you can add `#define _WIN32_WINNT 0x0501` on top of the `dlfcn.c` file.

**Comment by pali** [comment]
@akyunus0 have you tried adding that line?

**Comment by akyunus0** [comment]
@pali yes, and it worked. Thank you

**Comment by pali** [comment]
@akyunus0: great! I created pull request with fix: https://github.com/dlfcn-win32/dlfcn-win32/pull/76
