### ISSUE TITLE
AppVeyor test problems

### ISSUE THREAD

**Issue by traversaro** [dlfcn-win32/dlfcn-win32#77]
I am not sure what happened, but the AppVeyor tests now do not work anymore correctly, do not report the status on the PRs, and now fail on the latest master (see https://ci.appveyor.com/project/dlfcn-win32/dlfcn-win32/builds/34102698 and https://ci.appveyor.com/project/dlfcn-win32/dlfcn-win32/builds/34488023). However, the failures seems due to some change in how the AppVeyor configuration are interpreted (i.e. the wide configuration matrix generated in the past is not correctly generated anymore).

**Comment by pali** [comment]
You can try to disable AppVeyor and then enable it again.

**Comment by traversaro** [comment]
In particular, it seems that the `appveyor.yml` file is now ignored, and the solution in `dlfcn-win32\visual-studio\12\dlfcn-win32.sln` is automatically used.

**Comment by pali** [comment]
AppVeyor should be fixed now. Now last commit in master branch is being retested.

On page https://ci.appveyor.com/account/dlfcn-win32/authorizations I reinstalled github integration.

**Comment by traversaro** [comment]
Thanks a lot @pali !
