### ISSUE TITLE
Using dlfcn-win32 as a subproject of libbacktrace, gollvm

### ISSUE THREAD

**Issue by advancedwebdeveloper** [dlfcn-win32/dlfcn-win32#78]
Hi there.
I was investigating what could be patch on 32bit and 64bit Windows 10, for [https://go.googlesource.com/gollvm/](https://go.googlesource.com/gollvm/). That project, in turn, depend on [https://github.com/ianlancetaylor/libbacktrace](https://github.com/ianlancetaylor/libbacktrace).

In case if I would try to build libbacktrace alone (other dependencies of gollvm also have similar enforcement, on CMake) - CMake tried to read the config and perform a check on dlfcn.h. I think that is the first checked header file - and it was predicatively reporting that it was missing.

I was curious if there could be some option to use your project - but I am unsure where and how it used, for gollvm (and where).

Please share your thoughts.
I wonder about (at least) be able to pass header checks, by using your source code.

Hence that I have formed a cross-issue:
[https://github.com/ianlancetaylor/libbacktrace/issues/46](https://github.com/ianlancetaylor/libbacktrace/issues/46)
. So you are welcome to comment something, out there, as well.

Ivan

**Comment by advancedwebdeveloper** [comment]
I presume that this header

> -- Looking for link.h
> -- Looking for link.h - not found

is also related.

[https://github.molgen.mpg.de/git-mirror/glibc/blob/master/include/link.h#L1](https://github.molgen.mpg.de/git-mirror/glibc/blob/master/include/link.h#L1) threw [https://github.molgen.mpg.de/git-mirror/glibc/blob/master/include/link.h#L2](https://github.molgen.mpg.de/git-mirror/glibc/blob/master/include/link.h#L2) contains such a claim:

> Data structure for communication from the run-time dynamic linker for loaded ELF shared objects.
. It looks like it would have zero sense to have this header checked, if dlfcn-win32 would be used (as a drop-in replacement).

Ivan

**Comment by traversaro** [comment]
Hi @advancedwebdeveloper, 
   the `dlfcn-win32` library is composed only by the `dlfcn.h` and `dlfcn.c`, that can be either be used compiled as a library on its own and then used in your build system, or including directly the files in your project (in this case anyhow note that you need to comply with the LGPL license under which dlfcn-win32 is licensed. 

As explained by https://github.com/ianlancetaylor/libbacktrace/issues/46#issuecomment-671125007, some build systems check if the system provides headers such as `dlfcn.h`, but depending on the project it is possible that the project is able to compile even if a given system header is not found. 

Regarding the `link.h` header, `dlfcn-win32` does not provide it. 

If this answer is ok for you, feel free to close the issue, thanks.

**Comment by traversaro** [comment]
I am closing the issue due to the lack of further responses, feel free to comment if there are further doubts.
