### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by traversaro** [dlfcn-win32/dlfcn-win32#91]
Once https://github.com/dlfcn-win32/dlfcn-win32/pull/72 is merged, probably it make sense to do a new release (minor as it adds a new functionality).

**Comment by pali** [comment]
I'm planning to look at issue https://github.com/dlfcn-win32/dlfcn-win32/issues/87 after https://github.com/dlfcn-win32/dlfcn-win32/pull/72 is merged, it should not be hard.

**Comment by traversaro** [comment]
Great, thanks!

**Comment by pali** [comment]
dladdr() is fully implemented and current master branch tested on different configuration & compilator. So ready for a new release? Maybe extending documentation?

**Comment by traversaro** [comment]
Yes, I wanted to revise the README a bit to mention dladdr, but there is no need to block the release on that, we can easily release v1.3.1 with improved docs.

**Comment by traversaro** [comment]
I prepared a draft releases note on the v1.3.0 release in https://github.com/dlfcn-win32/dlfcn-win32/releases/tag/v1.3.0, if there are no comments I plan to switch the release from "prerelease" to actual release in one day.

**Comment by pali** [comment]
I'm fine with it.

**Comment by traversaro** [comment]
v1.3.0 available at https://github.com/dlfcn-win32/dlfcn-win32/releases/tag/v1.3.0 .
